name: Build/test suite

on:
  - push
  - pull_request

jobs:
  build:
    name: Run Fortran tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
            sudo apt-get --yes install ccache
            sudo apt-get update -q -y
            sudo apt-get install -y libopenblas-base libopenblas-dev
            pip3 install sparse-ir xprec

      - name: Test fortran interface
        run: |
          cp Makefile.gfortran_openblas Makefile
          pwd
          ls -l
          ./runtest.sh
